use_default_settings: true

general:
  debug: false
  instance_name: DraftDesk Search

server:
  bind_address: 0.0.0.0
  port: 8080
  secret_key: change-this-local-secret
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: zh-CN
  formats:
    - html
    - json

engines:
  - name: bing
    disabled: false
  - name: brave
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: google
    disabled: false
  - name: wikipedia
    disabled: false
