import type { Config, Plan, Source } from "./schema";
export const defaultConfig: Config = {
  baseUrl:
    "https://YOUR-WORKSPACE-ID.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
  model: "qwen3.8-flash",
  profile:
    "公众号、小红书，面向普通职场人与创作者。提供可操作的 AI 工作流、实测计划和小型应用机会。",
  dailyTokenLimit: 600000,
};
export const defaultSources: Source[] = [
  {
    id: "aihot",
    name: "AIHOT 精选资讯",
    type: "rss",
    url: "https://aihot.news/feed.xml",
    sourceType: "media",
    enabled: true,
    note: "聚合线索；重要结论优先找官方原文。商用转载遵循来源授权。",
  },
  {
    id: "aihot-products",
    name: "AIHOT 产品动态",
    type: "rss",
    url: "https://aihot.news/feed/category/ai-products.xml",
    sourceType: "product",
    enabled: true,
    note: "新产品发现，不等同真实用户需求。",
  },
  {
    id: "trends-us",
    name: "Google Trends · 美国",
    type: "trends",
    region: "US",
    sourceType: "trend",
    enabled: true,
    note: "地域热榜与分桶热度，不能推断中国需求或任意词历史指数。",
  },
  {
    id: "github",
    name: "GitHub 活跃项目",
    type: "github",
    query: "topic:ai stars:>50",
    sourceType: "repository",
    enabled: true,
    note: "以更新时间排序；Stars 是累计关注，不能解释为付费需求或增长率。",
  },
  {
    id: "web",
    name: "Tavily 网页搜索",
    type: "web",
    sourceType: "other",
    enabled: true,
    note: "需要 Tavily Key，按策略关键词、域名和时间窗口搜索。搜索摘要不冒充全文。",
  },
];
const base = {
  audience: "普通职场人与创作者",
  keywords: ["AI 工作流 产品更新 内容创作"],
  excludeKeywords: ["融资估值", "股价"],
  includeDomains: [],
  lookbackDays: 7,
  maxEvidence: 18,
  maxQueries: 2,
  maxItems: 4,
  maxModelCalls: 4,
  maxTokens: 200000,
  scheduleEnabled: false,
  dailyTime: "01:00",
  publishPolicy: "manual" as const,
};
export const defaultPlans: Plan[] = [
  {
    ...base,
    id: "daily-editorial",
    name: "每天值得写的 AI 变化",
    kind: "editorial",
    goal: "发现和个人工作有关的 AI 变化，提出有读者收益、有实测步骤的公众号与小红书选题；同一事件合并多个来源。",
    sourceIds: ["aihot", "web"],
    dailyTime: "01:00",
  },
  {
    ...base,
    id: "trend-radar",
    name: "热词与内容机会",
    kind: "trends",
    goal: "观察真实趋势信号，解释地域、时效、意图和内容机会；没有历史值就不判断增速。",
    sourceIds: ["trends-us", "web"],
    keywords: ["AI", "ChatGPT", "Claude", "Gemini"],
    dailyTime: "01:15",
  },
  {
    ...base,
    id: "small-products",
    name: "一人可验证的应用机会",
    kind: "opportunity",
    goal: "将产品变化、真实用户抱怨和替代方案连接起来，找出可用一周实验验证的微型应用；没有需求证据就列为假设。",
    sourceIds: ["aihot-products", "github", "web"],
    keywords: ["AI 创作者 工具 痛点 替代 太贵"],
    maxItems: 3,
    dailyTime: "01:30",
  },
  {
    ...base,
    id: "people-watch",
    name: "人物与作者观察",
    kind: "people",
    goal: "追踪指定公开作者的作品、方法与公开观点；核对同名身份，不收集个人隐私，不虚构公众号全文。",
    sourceIds: ["web"],
    keywords: ["AI 实用 工作流 作者 教程"],
    maxItems: 3,
    dailyTime: "01:45",
  },
];
