import type { Config, Plan, Source } from "./schema";
export const defaultConfig: Config = {
  baseUrl:
    "https://YOUR-WORKSPACE-ID.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
  model: "qwen3.8-flash",
  profile:
    "公众号、小红书，面向普通职场人与创作者。提供可操作的 AI 工作流、实测计划和小型应用机会。",
  dailyTokenLimit: 600000,
};
export const defaultSources: Source[] = [
  {id:"openai-official",name:"OpenAI 官方更新",type:"rss",url:"https://openai.com/news/rss.xml",officialDomains:["help.openai.com","platform.openai.com"],sourceType:"official",enabled:true,note:"官方产品声明；用户体验和效果仍需独立验证。"},
  {id:"google-ai-official",name:"Google AI 官方更新",type:"rss",url:"https://blog.google/innovation-and-ai/technology/ai/rss/",officialDomains:["docs.cloud.google.com","support.google.com","workspaceupdates.googleblog.com"],sourceType:"official",enabled:true,note:"官方 AI 产品更新；用内容筛选词排除无关产业新闻。"},
  {id:"simon-practice",name:"Simon Willison 实践文章",type:"rss",url:"https://simonwillison.net/atom/entries/",sourceType:"other",enabled:true,note:"作者实践与作品线索，不能代替厂商定价和功能公告。"},
  {id:"v2ex-problems",name:"V2EX 技术讨论",type:"rss",url:"https://www.v2ex.com/feed/tab/tech.xml",sourceType:"community",enabled:true,note:"公开求助和使用反馈；包含推广与个体意见，需核对原文，不代表普遍市场。"},
  {
    id: "aihot",
    name: "AIHOT 精选资讯",
    type: "rss",
    url: "https://aihot.news/feed.xml",
    sourceType: "media",
    enabled: true,
    note: "聚合线索；重要结论优先找官方原文。商用转载遵循来源授权。",
  },
  {
    id: "aihot-products",
    name: "AIHOT 产品动态",
    type: "rss",
    url: "https://aihot.news/feed/category/ai-products.xml",
    sourceType: "product",
    enabled: true,
    note: "新产品发现，不等同真实用户需求。",
  },
  {
    id: "trends-us",
    name: "Google Trends · 美国",
    type: "trends",
    region: "US",
    sourceType: "trend",
    enabled: true,
    note: "地域热榜与分桶热度，不能推断中国需求或任意词历史指数。",
  },
  {id:"baidu-hot",name:"百度热搜 · 中国",type:"hotlist",url:"https://top.baidu.com/board?tab=realtime",sourceType:"trend",enabled:true,note:"官方热搜榜；指数是百度平台内热度，不等于搜索量或市场需求。只保留与策略内容筛选词匹配的词条。"},
  {id:"weibo-hot",name:"微博热搜 · 中国",type:"hotlist",url:"https://s.weibo.com/top/summary?cate=realtimehot",sourceType:"trend",enabled:false,note:"官方 HTML 入口；匿名访问返回访客验证页，保持停用。热搜数据请用「微博热搜 · 官方接口」来源。"},
  {id:"weibo-hotsearch",name:"微博热搜 · 官方接口",type:"hotlist",url:"https://weibo.com/ajax/side/hotSearch",sourceType:"trend",enabled:true,note:"网页版侧栏同源的官方公开 JSON 接口，匿名可用，含实时热度值。仅是平台热度线索，不等于需求或增长。"},
  {id:"bilibili-popular",name:"B站热门 · 官方接口",type:"hotlist",url:"https://api.bilibili.com/x/web-interface/popular",sourceType:"trend",enabled:true,note:"B站综合热门视频官方公开接口，匿名可用，含播放量。本机到其 CDN 链路有波动，已内置重试；失败会在运行记录留痕。热门视频是内容热度线索，不代表话题搜索需求。"},
  {id:"dailyhot-bilibili",name:"B站热门 · 聚合补充",type:"aggregated",query:"bilibili",sourceType:"trend",enabled:false,note:"本机试跑曾超时、复测成功，存在波动；默认停用，可检测连接后手动启用。"},
  {id:"dailyhot-weibo",name:"微博热搜 · 聚合补充",type:"aggregated",query:"weibo",sourceType:"trend",enabled:false,note:"本机试跑上游返回异常，默认停用；可在网络可达时手动启用并验证。"},
  {id:"dailyhot-zhihu",name:"知乎热榜 · 聚合补充",type:"aggregated",query:"zhihu",sourceType:"trend",enabled:true,note:"经本地 DailyHotApi 获取榜单标题和原平台链接；不代表问题内容已核实。"},
  {id:"dailyhot-douyin",name:"抖音热点 · 聚合补充",type:"aggregated",query:"douyin",sourceType:"trend",enabled:true,note:"经本地 DailyHotApi 获取；仅是公开热点线索，不是登录后的创作者活动。"},
  {id:"dailyhot-kuaishou",name:"快手热点 · 聚合补充",type:"aggregated",query:"kuaishou",sourceType:"trend",enabled:false,note:"本机试跑上游返回异常，默认停用；仅是公开热点线索，不是登录后的创作者活动。"},
  {id:"dailyhot-toutiao",name:"头条热榜 · 聚合补充",type:"aggregated",query:"toutiao",sourceType:"trend",enabled:true,note:"经本地 DailyHotApi 获取榜单标题和原平台链接；重要结论再查原始报道。"},
  {id:"dailyhot-tieba",name:"贴吧热议 · 聚合补充",type:"aggregated",query:"tieba",sourceType:"trend",enabled:true,note:"经本地 DailyHotApi 获取公开讨论线索；个别帖子不代表普遍需求。"},
  {id:"dailyhot-juejin",name:"掘金热榜 · 聚合补充",type:"aggregated",query:"juejin",sourceType:"trend",enabled:true,note:"经本地 DailyHotApi 获取开发者内容线索；榜单不代表付费需求。"},
  {id:"github-trending",name:"GitHub Trending · 全球",type:"hotlist",url:"https://github.com/trending",sourceType:"repository",enabled:true,note:"GitHub 当日热门仓库；当日 Stars 仅是社区关注信号，不等于用户需求或市场增长。"},
  {id:"hacker-news-top",name:"Hacker News Top · 全球",type:"hotlist",url:"https://hacker-news.firebaseio.com/v0/topstories.json",sourceType:"community",enabled:true,note:"官方 Top Stories API；榜单分数表示 HN 社区关注，不是搜索热度。每次最多读取前 30 条。"},
  {id:"trends-gb",name:"Google Trends · 英国",type:"trends",region:"GB",sourceType:"trend",enabled:true,note:"英国近期搜索热榜；地域不同，不与中国或美国数值混算。"},
  {id:"trends-jp",name:"Google Trends · 日本",type:"trends",region:"JP",sourceType:"trend",enabled:true,note:"日本近期搜索热榜；按日本地域筛选。"},
  {id:"trends-tw",name:"Google Trends · 台湾地区",type:"trends",region:"TW",sourceType:"trend",enabled:true,note:"台湾地区近期搜索热榜；不等同中国大陆热度。"},
  {id:"trends-in",name:"Google Trends · 印度",type:"trends",region:"IN",sourceType:"trend",enabled:true,note:"印度近期搜索热榜；按印度地域筛选。"},
  {id:"trends-kr",name:"Google Trends · 韩国",type:"trends",region:"KR",sourceType:"trend",enabled:true,note:"韩国近期搜索热榜；按韩国地域筛选。"},
  {id:"trends-de",name:"Google Trends · 德国",type:"trends",region:"DE",sourceType:"trend",enabled:true,note:"德国近期搜索热榜；按德国地域筛选。"},
  {id:"producthunt-feed",name:"Product Hunt · 新产品",type:"rss",url:"https://www.producthunt.com/feed",sourceType:"product",enabled:true,note:"官方产品 Feed，是新产品线索而非热门搜索排行榜；适合应用机会分析。"},
  {id:"suggest-cn",name:"百度搜索联想 · 中文需求雷达",type:"suggest",url:"https://www.baidu.com/sugrec",query:"替代软件,怎么查,多少钱,自动",sourceType:"trend",enabled:true,note:"需求形状种子（替代软件/怎么查/多少钱/自动）：不设话题，直接捞各领域正在形成的搜索意图；联想词不是搜索量数据，机会需核验竞争与供给。"},
  {id:"suggest-global",name:"Google 搜索联想 · 全球需求雷达",type:"suggest",query:"alternative to,how to check,is there a tool,automate",sourceType:"trend",enabled:true,note:"需求形状种子（alternative/how to check/is there a tool/automate）：捕捉全球未满足的工具与信息需求；不是已验证需求。"},
  {
    id: "github",
    name: "GitHub 活跃项目",
    type: "github",
    query: "topic:ai stars:>50",
    sourceType: "repository",
    enabled: true,
    note: "以更新时间排序；Stars 是累计关注，不能解释为付费需求或增长率。",
  },
  {
    id: "web",
    name: "Tavily 网页搜索",
    type: "web",
    sourceType: "other",
    enabled: true,
    note: "需要 Tavily Key，按策略关键词、域名和时间窗口搜索。搜索摘要不冒充全文。",
  },
];
const base = {
  audience: "普通职场人与创作者",
  keywords: ["AI 工作流 产品更新 内容创作"],
  excludeKeywords: ["融资估值", "股价"],
  includeDomains: [],
  lookbackDays: 7,
  maxEvidence: 18,
  maxQueries: 2,
  maxItems: 4,
  maxModelCalls: 8,
  maxTokens: 400000,
  scheduleEnabled: false,
  dailyTime: "01:00",
  publishPolicy: "manual" as const,
};
export const defaultPlans: Plan[] = [
  {
    ...base,
    id: "daily-editorial",
    name: "每天值得写的 AI 变化",
    kind: "editorial",
    goal: "发现和个人工作有关的 AI 变化，提出有读者收益、有实测步骤的公众号与小红书选题；同一事件合并多个来源。",
    sourceIds: ["openai-official", "google-ai-official", "aihot", "web"],
    keywords: ["Gemini 文档办公", "剪映 字幕 工作流"],
    focusTerms: ["ChatGPT","Gemini","NotebookLM","剪映","字幕","文档","会议","表格","创作","writing","document","spreadsheet","video","workflow"],
    maxQueries: 4,
    dailyTime: "01:00",
  },
  {
    ...base,
    id: "trend-radar",
    requireMetrics: true,
    name: "热词与内容机会",
    kind: "trends",
    goal: "采集层不设话题门禁：任何上榜热度（Google Trends、搜索联想、中文热榜）都进入观察，AI 话题之外的社会热度同样重要。分析层对每条热度评估三种转化：① AI 内容角度（用 AI 复刻、分析、避坑、教学的内容机会）；② web/app 工具机会（查询站、计算器、监控提醒、状态页等配套缺口）；③ SEO/站群价值（搜索意图明确且供给不足的词）。三种转化都不成立才放弃。没有历史值就不判断增速。",
    sourceIds: ["suggest-cn", "suggest-global", "trends-us", "trends-gb", "baidu-hot", "weibo-hotsearch", "bilibili-popular", "dailyhot-juejin", "web"],
    keywords: [],
    focusTerms: [],
    dailyTime: "01:15",
  },
  {
    ...base,
    id: "small-products",
    name: "一人可验证的应用机会",
    kind: "opportunity",
    goal: "将产品变化、真实用户抱怨和替代方案连接起来，找出可用一周实验验证的微型应用；同时关注 SEO/站群与 web-app 配套机会：新平台发布后推演其限制查询、状态监控、额度计算等配套缺口。没有需求证据就列为假设。",
    sourceIds: ["v2ex-problems", "aihot-products", "producthunt-feed", "github", "web"],
    keywords: ["AI 字幕纠错", "会议纪要 负责人 核对", "替代", "太麻烦", "手动", "额度", "监控 提醒", "自动化"],
    focusTerms: ["字幕","会议","纪要","文档","剪辑","创作者","工作流","AI","ChatGPT","Claude","Gemini"],
    maxQueries: 4,
    maxItems: 3,
    dailyTime: "01:30",
  },
  {...base,id:"creator-activities",name:"AI 与 Vibe Coding 创作活动",kind:"activities",goal:"搜罗四平台适合个人AI工作流、Vibe Coding、独立开发、软件实测创作者参与的流量激励与征稿活动。核对投稿时间、资格、奖励和原始规则链接；每活动生成3–5个内容方向，资料不足不凑数。",audience:"个人创作者与独立开发者；粉丝数、学生身份及平台邀约资格未知",sourceIds:["web"],keywords:["B站 AI 创作大赛","抖音 AI 创作活动","快手 AI 创作大赛","小红书 AI 编程 活动"],includeDomains:["bilibili.com","douyin.com","douyinstatic.com","kuaishou.com","xiaohongshu.com"],lookbackDays:365,maxQueries:8,maxEvidence:24,maxItems:4,maxModelCalls:8,dailyTime:"02:30"},
];

// 决策层 persona 默认种子（需求 §14 附录 A）：仅作首版初始化，UI 可改，不写死业务规则。
export const defaultPersona = {
  domains: {
    do: ["AI / AIGC 工具与创作", "独立开发 / VibeCoding / 出海 SaaS", "生财搞钱方法论与案例", "自媒体运营 / 内容矩阵"],
    dont: [] as string[],
  },
  goals: ["企业 AI / FDE 订单线索", "生财方法论涨粉", "个人知识沉淀", "技术 / 最新资讯分享涨粉"],
  platformRules: [
    { contentType: "测评类", scale: "中长", platforms: ["公众号长文", "小红书"] },
    { contentType: "资讯", scale: "长", platforms: ["公众号", "小红书"] },
    { contentType: "资讯", scale: "短", platforms: ["贴图号(视频号)", "Threads(英文)"] },
    { contentType: "成果分享", scale: "中", platforms: ["公众号长文", "小红书"] },
    { contentType: "英文短评", scale: "短", platforms: ["Threads"] },
  ],
  imageOnly: true,
  scoring: {
    threshold: 3.5,
    dimensions: [
      { name: "业务/人设相关度", weight: 0.25 },
      { name: "我能写透（有实操）", weight: 0.2 },
      { name: "流量/搜索长尾", weight: 0.2 },
      { name: "商业转化潜力", weight: 0.15 },
      { name: "时效性", weight: 0.1 },
      { name: "争议/讨论度", weight: 0.1 },
    ],
  },
  redLines: [
    "纯搬运，无本人观点/无实操增量",
    "数据与已核实事实冲突（失真）",
    "蹭敏感/争议热点（政治、低俗等）",
    "触碰硬禁忌：出镜直播/私域拉群/电商囤货/灰产",
    "标题党无干货、恐吓式营销",
  ],
  style: {
    principles: ["结论先行", "表格", "PHASE 分阶段"],
    tone: "专业自信、同行口吻",
    forbidden: ["震惊", "速速收藏", "家人们"],
    notes: "数据可溯源，不编造通过率与收益；对外稿必过「去 AI 味」处理。",
  },
};
