import type { Config, Plan, Source } from "./schema";
export const defaultConfig: Config = {
  baseUrl:
    "https://YOUR-WORKSPACE-ID.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
  model: "qwen3.8-flash",
  profile:
    "公众号、小红书，面向普通职场人与创作者。提供可操作的 AI 工作流、实测计划和小型应用机会。",
  dailyTokenLimit: 600000,
};
export const defaultSources: Source[] = [
  {id:"openai-official",name:"OpenAI 官方更新",type:"rss",url:"https://openai.com/news/rss.xml",officialDomains:["help.openai.com","platform.openai.com"],sourceType:"official",enabled:true,note:"官方产品声明；用户体验和效果仍需独立验证。"},
  {id:"google-ai-official",name:"Google AI 官方更新",type:"rss",url:"https://blog.google/innovation-and-ai/technology/ai/rss/",officialDomains:["docs.cloud.google.com","support.google.com","workspaceupdates.googleblog.com"],sourceType:"official",enabled:true,note:"官方 AI 产品更新；用内容筛选词排除无关产业新闻。"},
  {id:"simon-practice",name:"Simon Willison 实践文章",type:"rss",url:"https://simonwillison.net/atom/entries/",sourceType:"other",enabled:true,note:"作者实践与作品线索，不能代替厂商定价和功能公告。"},
  {id:"v2ex-problems",name:"V2EX 技术讨论",type:"rss",url:"https://www.v2ex.com/feed/tab/tech.xml",sourceType:"community",enabled:true,note:"公开求助和使用反馈；包含推广与个体意见，需核对原文，不代表普遍市场。"},
  {
    id: "aihot",
    name: "AIHOT 精选资讯",
    type: "rss",
    url: "https://aihot.news/feed.xml",
    sourceType: "media",
    enabled: true,
    note: "聚合线索；重要结论优先找官方原文。商用转载遵循来源授权。",
  },
  {
    id: "aihot-products",
    name: "AIHOT 产品动态",
    type: "rss",
    url: "https://aihot.news/feed/category/ai-products.xml",
    sourceType: "product",
    enabled: true,
    note: "新产品发现，不等同真实用户需求。",
  },
  {
    id: "trends-us",
    name: "Google Trends · 美国",
    type: "trends",
    region: "US",
    sourceType: "trend",
    enabled: true,
    note: "地域热榜与分桶热度，不能推断中国需求或任意词历史指数。",
  },
  {id:"baidu-hot",name:"百度热搜 · 中国",type:"hotlist",url:"https://top.baidu.com/board?tab=realtime",sourceType:"trend",enabled:true,note:"官方热搜榜；指数是百度平台内热度，不等于搜索量或市场需求。只保留与策略内容筛选词匹配的词条。"},
  {id:"weibo-hot",name:"微博热搜 · 中国",type:"hotlist",url:"https://s.weibo.com/top/summary?cate=realtimehot",sourceType:"trend",enabled:false,note:"官方入口；匿名访问可能返回访客验证页，失败会记录来源异常。需在允许的访问方式下启用，不绕过验证。"},
  {id:"dailyhot-bilibili",name:"B站热门 · 聚合补充",type:"aggregated",query:"bilibili",sourceType:"trend",enabled:false,note:"本机试跑曾超时、复测成功，存在波动；默认停用，可检测连接后手动启用。"},
  {id:"dailyhot-weibo",name:"微博热搜 · 聚合补充",type:"aggregated",query:"weibo",sourceType:"trend",enabled:false,note:"本机试跑上游返回异常，默认停用；可在网络可达时手动启用并验证。"},
  {id:"dailyhot-zhihu",name:"知乎热榜 · 聚合补充",type:"aggregated",query:"zhihu",sourceType:"trend",enabled:true,note:"经本地 DailyHotApi 获取榜单标题和原平台链接；不代表问题内容已核实。"},
  {id:"dailyhot-douyin",name:"抖音热点 · 聚合补充",type:"aggregated",query:"douyin",sourceType:"trend",enabled:true,note:"经本地 DailyHotApi 获取；仅是公开热点线索，不是登录后的创作者活动。"},
  {id:"dailyhot-kuaishou",name:"快手热点 · 聚合补充",type:"aggregated",query:"kuaishou",sourceType:"trend",enabled:false,note:"本机试跑上游返回异常，默认停用；仅是公开热点线索，不是登录后的创作者活动。"},
  {id:"dailyhot-toutiao",name:"头条热榜 · 聚合补充",type:"aggregated",query:"toutiao",sourceType:"trend",enabled:true,note:"经本地 DailyHotApi 获取榜单标题和原平台链接；重要结论再查原始报道。"},
  {id:"dailyhot-tieba",name:"贴吧热议 · 聚合补充",type:"aggregated",query:"tieba",sourceType:"trend",enabled:true,note:"经本地 DailyHotApi 获取公开讨论线索；个别帖子不代表普遍需求。"},
  {id:"dailyhot-juejin",name:"掘金热榜 · 聚合补充",type:"aggregated",query:"juejin",sourceType:"trend",enabled:true,note:"经本地 DailyHotApi 获取开发者内容线索；榜单不代表付费需求。"},
  {id:"github-trending",name:"GitHub Trending · 全球",type:"hotlist",url:"https://github.com/trending",sourceType:"repository",enabled:true,note:"GitHub 当日热门仓库；当日 Stars 仅是社区关注信号，不等于用户需求或市场增长。"},
  {id:"hacker-news-top",name:"Hacker News Top · 全球",type:"hotlist",url:"https://hacker-news.firebaseio.com/v0/topstories.json",sourceType:"community",enabled:true,note:"官方 Top Stories API；榜单分数表示 HN 社区关注，不是搜索热度。每次最多读取前 30 条。"},
  {id:"trends-gb",name:"Google Trends · 英国",type:"trends",region:"GB",sourceType:"trend",enabled:true,note:"英国近期搜索热榜；地域不同，不与中国或美国数值混算。"},
  {id:"trends-jp",name:"Google Trends · 日本",type:"trends",region:"JP",sourceType:"trend",enabled:true,note:"日本近期搜索热榜；按日本地域筛选。"},
  {id:"trends-tw",name:"Google Trends · 台湾地区",type:"trends",region:"TW",sourceType:"trend",enabled:true,note:"台湾地区近期搜索热榜；不等同中国大陆热度。"},
  {id:"trends-in",name:"Google Trends · 印度",type:"trends",region:"IN",sourceType:"trend",enabled:true,note:"印度近期搜索热榜；按印度地域筛选。"},
  {id:"trends-kr",name:"Google Trends · 韩国",type:"trends",region:"KR",sourceType:"trend",enabled:true,note:"韩国近期搜索热榜；按韩国地域筛选。"},
  {id:"trends-de",name:"Google Trends · 德国",type:"trends",region:"DE",sourceType:"trend",enabled:true,note:"德国近期搜索热榜；按德国地域筛选。"},
  {id:"producthunt-feed",name:"Product Hunt · 新产品",type:"rss",url:"https://www.producthunt.com/feed",sourceType:"product",enabled:true,note:"官方产品 Feed，是新产品线索而非热门搜索排行榜；适合应用机会分析。"},
  {
    id: "github",
    name: "GitHub 活跃项目",
    type: "github",
    query: "topic:ai stars:>50",
    sourceType: "repository",
    enabled: true,
    note: "以更新时间排序；Stars 是累计关注，不能解释为付费需求或增长率。",
  },
  {
    id: "web",
    name: "Tavily 网页搜索",
    type: "web",
    sourceType: "other",
    enabled: true,
    note: "需要 Tavily Key，按策略关键词、域名和时间窗口搜索。搜索摘要不冒充全文。",
  },
];
const base = {
  audience: "普通职场人与创作者",
  keywords: ["AI 工作流 产品更新 内容创作"],
  excludeKeywords: ["融资估值", "股价"],
  includeDomains: [],
  lookbackDays: 7,
  maxEvidence: 18,
  maxQueries: 2,
  maxItems: 4,
  maxModelCalls: 4,
  maxTokens: 200000,
  scheduleEnabled: false,
  dailyTime: "01:00",
  publishPolicy: "manual" as const,
};
export const defaultPlans: Plan[] = [
  {
    ...base,
    id: "daily-editorial",
    name: "每天值得写的 AI 变化",
    kind: "editorial",
    goal: "发现和个人工作有关的 AI 变化，提出有读者收益、有实测步骤的公众号与小红书选题；同一事件合并多个来源。",
    sourceIds: ["openai-official", "google-ai-official", "aihot", "web"],
    keywords: ["Gemini 文档办公", "剪映 字幕 工作流"],
    focusTerms: ["ChatGPT","Gemini","NotebookLM","剪映","字幕","文档","会议","表格","创作","writing","document","spreadsheet","video","workflow"],
    maxQueries: 4,
    dailyTime: "01:00",
  },
  {
    ...base,
    id: "trend-radar",
    requireMetrics: true,
    name: "热词与内容机会",
    kind: "trends",
    goal: "观察真实趋势信号，解释地域、时效、意图和内容机会；没有历史值就不判断增速。",
    sourceIds: ["dailyhot-juejin", "dailyhot-zhihu", "baidu-hot", "trends-us", "web"],
    keywords: ["AI", "人工智能", "AIGC", "大模型", "AI视频", "Vibe Coding", "ChatGPT", "Gemini"],
    focusTerms: ["AI", "人工智能", "AIGC", "大模型", "AI视频", "视频生成", "Vibe Coding", "AI编程", "ChatGPT", "NotebookLM"],
    dailyTime: "01:15",
  },
  {
    ...base,
    id: "small-products",
    name: "一人可验证的应用机会",
    kind: "opportunity",
    goal: "将产品变化、真实用户抱怨和替代方案连接起来，找出可用一周实验验证的微型应用；没有需求证据就列为假设。",
    sourceIds: ["v2ex-problems", "aihot-products", "producthunt-feed", "web"],
    keywords: ["AI 字幕纠错", "会议纪要 负责人 核对"],
    focusTerms: ["字幕","会议","纪要","文档","剪辑","创作者","工作流","AI","ChatGPT","Claude","Gemini"],
    maxQueries: 4,
    maxItems: 3,
    dailyTime: "01:30",
  },
  {
    ...base,
    id: "people-watch",
    name: "人物与作者观察",
    kind: "people",
    goal: "追踪指定公开作者的作品、方法与公开观点；核对同名身份，不收集个人隐私，不虚构公众号全文。",
    sourceIds: ["web"],
    keywords: ["AI 实用 工作流 作者 教程"],
    maxItems: 3,
    dailyTime: "01:45",
  },
  {...base,id:"creator-activities",name:"AI 与 Vibe Coding 创作活动",kind:"activities",goal:"搜罗四平台适合个人AI工作流、Vibe Coding、独立开发、软件实测创作者参与的流量激励与征稿活动。核对投稿时间、资格、奖励和原始规则链接；每活动生成3–5个内容方向，资料不足不凑数。",audience:"个人创作者与独立开发者；粉丝数、学生身份及平台邀约资格未知",sourceIds:["web"],keywords:["B站 AI 创作大赛","抖音 AI 创作活动","快手 AI 创作大赛","小红书 AI 编程 活动"],includeDomains:["bilibili.com","douyin.com","douyinstatic.com","kuaishou.com","xiaohongshu.com"],lookbackDays:365,maxQueries:8,maxEvidence:24,maxItems:4,maxModelCalls:6,dailyTime:"02:30"},
];
