"use client";
import {useState} from "react";
import {activityPlatforms,activityPageSchema,isActivityIndexUrl} from "../core/activity-import";
import {activityBatchSchema,activityBatchDecision,manualActivityDeadline,type ActivityBatchItem} from "../core/activity-batch";
import {api,Field} from "./ui";
export function ActivityImport({onChange,onRun,active}:{onChange:()=>Promise<void>;onRun:()=>void;active:boolean}){
 const [platform,setPlatform]=useState(0),[title,setTitle]=useState(""),[url,setUrl]=useState(""),[text,setText]=useState(""),[deadlineDate,setDeadlineDate]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[evidenceId,setEvidenceId]=useState("");
 const [batch,setBatch]=useState<ActivityBatchItem[]>([]),[batchWarnings,setBatchWarnings]=useState<string[]>([]),[hasBatch,setHasBatch]=useState(false),[keywordText,setKeywordText]=useState("AI, AIGC, AI视频, Vibe Coding, vibecoding, AI编程, AI工具");
 const keywords=keywordText.split(/[,，\n]/).map(x=>x.trim()).filter(Boolean);
 const reset=()=>setEvidenceId("");
 async function load(files?:FileList){if(!files?.length)return;try{if(files.length>4)throw Error("最多同时导入四个平台的四份文件。");const raw=await Promise.all([...files].map(async file=>{if(file.size>5000000)throw Error("单个文件超过 5MB。请缩小采集范围。");return JSON.parse((await file.text()).replace(/^\uFEFF/,""));}));if(raw.every(x=>x.schemaVersion==="draftdesk.activity-batch.v1")){const data=raw.map(x=>activityBatchSchema.parse(x));const seen=new Set<string>();const items=data.flatMap(x=>x.items).filter(x=>{const key=`${x.platform}|${x.url}|${x.title}`;if(seen.has(key))return false;seen.add(key);return true;});setBatch(items);setBatchWarnings(data.flatMap(x=>x.warnings.map(w=>`${x.platform}：${w}`)));setHasBatch(true);const words=[...new Set(data.flatMap(x=>x.keywords))];setKeywordText(words.join(", ")||keywordText);}else if(raw.length===1){const data=activityPageSchema.parse(raw[0]);setBatch([]);setBatchWarnings([]);setHasBatch(false);setTitle(data.title);setUrl(data.url);setText(data.text);setDeadlineDate("");reset();}else throw Error("多文件导入只支持批量活动包。");setError("");}catch(e){setError(e instanceof Error?`导入失败：${e.message}`:"导入失败：需要合法的官方活动 JSON。");}}
 async function run(){setBusy(true);setError("");try{const check=manualActivityDeadline(deadlineDate,text);if(!check.eligible)throw Error(check.reason);const value=activityPageSchema.parse({schemaVersion:"draftdesk.activity-page.v1",title,url,text});let id=evidenceId;if(!id){const r=await api("activity-evidence",value);id=r.evidenceId;setEvidenceId(id);}await api("jobs",{planId:"creator-activities",evidenceIds:[id]});await onChange();onRun();}catch(e){setError(e instanceof Error?e.message:"分析失败");}finally{setBusy(false);}}
 async function runBatch(){setBusy(true);setError("");try{const selected=batch.filter(x=>activityBatchDecision(x,keywords).eligible);if(!selected.length)throw Error("没有截止时间明确、未过期且含规则详情的目标活动；请检查采集结果。");if(selected.length>24)throw Error("合格活动超过单次研究的 24 条上限。请缩小目标关键词，或分平台导入；未提交的线索仍留在预览中。");if(keywords.length>8)throw Error("单次研究最多使用 8 个目标关键词，请合并相近词后重试。");const ids:string[]=[];for(const item of selected){const result=await api("activity-evidence",{schemaVersion:"draftdesk.activity-page.v1",title:item.title,url:item.url,text:`平台：${item.platform}\n${isActivityIndexUrl(item.url)?`官方活动中心定位：${item.sourceLocator}（此地址不是单条活动链接，分析结果须按标题复核）\n`:""}活动时间原文：${item.dateText}\n截止时间：${item.endsAt}\n${item.text}`});ids.push(result.evidenceId);}await api("jobs",{planId:"creator-activities",evidenceIds:ids,targetKeywords:keywords});await onChange();onRun();}catch(e){setError(e instanceof Error?e.message:"批量分析失败");}finally{setBusy(false);}}
 return <section className="surface activity-tools"><h2>从官方活动页导入</h2><p>登录留在你自己的 Chrome / Edge；工作台不接收密码和 Cookie。采集由你手动执行，分析只使用提交的规则，不进行网络搜索。</p>
 <h3>1 · 选择平台并登录</h3><Field label="平台"><select value={platform} onChange={e=>setPlatform(Number(e.target.value))}>{activityPlatforms.map((p,i)=><option key={p.name} value={i}>{p.name}</option>)}</select></Field><a href={activityPlatforms[platform].url} target="_blank" rel="noopener noreferrer">打开{activityPlatforms[platform].name}官方活动入口 ↗</a><p>{activityPlatforms[platform].entry}。在自己的 Chrome / Edge 完成登录；Codex 内置浏览器的登录状态不会同步。工作台不接收账号密码或 Cookie。</p>
 <h3>2 · 自动采集与核对</h3><p><a href="/activity-collector.zip" download>下载开源浏览器采集扩展</a>，解压后在 Chrome / Edge 的“扩展程序”页面开启开发者模式，选择“加载已解压的扩展程序”，选中含 manifest.json 的目录。已安装旧版请重新解压并在扩展页点“重新加载”。</p><p>在各平台创作者中心打开扩展，输入关键词及最多扫描页数，点击“打开活动页并采集”；扩展会导航到官方活动中心、等待列表加载，再开始采集。已在活动页时可直接采集。扩展会保留扫描到的线索供你核对；已过期、缺明确截止日期、只有摘要或不匹配关键词的条目不会进入 AI 分析。每个平台导出一个批量 JSON，可一次选择四份文件合并预览。抖音扫描当前月份，切换月份后可再运行；小红书、快手的年份与规则可能需要核对。不会自动报名或发布。</p>
 <Field label="导入扩展导出的活动 JSON（可同时选最多四份）"><input type="file" accept=".json,application/json" multiple disabled={busy} onChange={e=>{void load(e.target.files||undefined);e.target.value="";}}/></Field>
 <Field label="目标关键词（逗号分隔；同时限制批量采集后的 AI 分析）"><input value={keywordText} disabled={busy} onChange={e=>setKeywordText(e.target.value)} /></Field>
 {hasBatch&&<section><h3>批量采集预览 · {batch.length} 条</h3><p>可分析 {batch.filter(x=>activityBatchDecision(x,keywords).eligible).length} 条；其余保留为待核线索。单次研究最多分析 24 条、使用 8 个目标关键词；超过时请缩小范围或分平台导入。只有截止时间明确、未过期、命中关键词且取得规则详情的活动才会提交 AI。</p>{batchWarnings.map((x,i)=><p className="muted" key={i}>{x}</p>)}{batch.length===0?<p>本次没有读到活动。请检查登录状态、活动页是否加载完成和扩展提示，不能把 0 条当作平台没有活动。</p>:<ul>{batch.map((item,i)=>{const d=activityBatchDecision(item,keywords);return <li key={i}><strong>{item.platform} · {item.title}</strong> — {d.reason} · {item.dateText||"时间未知"} · <a href={item.url} target="_blank" rel="noopener noreferrer">{isActivityIndexUrl(item.url)?"活动中心，按标题查找":"单条官方规则"} ↗</a></li>})}</ul>}<button className="primary" disabled={busy||active||keywords.length>8||!batch.some(x=>activityBatchDecision(x,keywords).eligible)||batch.filter(x=>activityBatchDecision(x,keywords).eligible).length>24} onClick={()=>void runBatch()}>{busy?"正在导入…":"导入合格活动并运行 AI 分析"}</button></section>}
 <h3>3 · 预览材料并交给 AI</h3><Field label="活动名称"><input value={title} disabled={busy} onChange={e=>{setTitle(e.target.value);reset();}} maxLength={300}/></Field><Field label="官方活动地址"><input value={url} disabled={busy} onChange={e=>{setUrl(e.target.value);reset();}}/></Field><Field label="规则正文"><textarea rows={8} value={text} disabled={busy} maxLength={12000} onChange={e=>{setText(e.target.value);reset();}}/></Field><Field label="投稿截止日期（从规则正文核对）"><input type="date" value={deadlineDate} disabled={busy} onChange={e=>setDeadlineDate(e.target.value)}/></Field><p>{text.length} / 12000 字 · 规则原文须包含你填写的截止日期及年份。已过期或日期无法从原文核对的活动不会提交模型。</p>{deadlineDate&&text.trim().length>=50&&!manualActivityDeadline(deadlineDate,text).eligible&&<p className="error">{manualActivityDeadline(deadlineDate,text).reason}</p>}<button className="primary" disabled={busy||active||text.trim().length<50||title.trim().length<3||!url||!manualActivityDeadline(deadlineDate,text).eligible} onClick={()=>void run()}>{busy?"正在提交…":active?"活动分析进行中":"保存规则并分析（模型计费）"}</button>{evidenceId&&<p>原文已保存，失败可重试创建分析任务。</p>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
