"use client";
import {useState} from "react";
import {activityPlatforms,activityPageSchema} from "../core/activity-import";
import {activityBatchSchema,activityBatchDecision,type ActivityBatchItem} from "../core/activity-batch";
import {api,Field} from "./ui";
export function ActivityImport({onChange,onRun,active}:{onChange:()=>Promise<void>;onRun:()=>void;active:boolean}){
 const [platform,setPlatform]=useState(0),[title,setTitle]=useState(""),[url,setUrl]=useState(""),[text,setText]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[evidenceId,setEvidenceId]=useState("");
 const [batch,setBatch]=useState<ActivityBatchItem[]>([]),[batchWarnings,setBatchWarnings]=useState<string[]>([]),[keywordText,setKeywordText]=useState("AI, AIGC, AI视频, Vibe Coding, vibecoding, AI编程, AI工具");
 const keywords=keywordText.split(/[,，\n]/).map(x=>x.trim()).filter(Boolean);
 const reset=()=>setEvidenceId("");
 async function load(file?:File){if(!file)return;try{if(file.size>600000)throw Error("文件超过600KB。请缩小采集范围。");const raw=JSON.parse((await file.text()).replace(/^\uFEFF/,""));if(raw.schemaVersion==="draftdesk.activity-batch.v1"){const data=activityBatchSchema.parse(raw);setBatch(data.items);setBatchWarnings(data.warnings);setKeywordText(data.keywords.join(", ")||keywordText);}else{const data=activityPageSchema.parse(raw);setBatch([]);setTitle(data.title);setUrl(data.url);setText(data.text);reset();}setError("");}catch{setError("导入失败：需要合法的官方活动 JSON；批量包需包含活动时间和来源。");}}
 async function run(){setBusy(true);setError("");try{const value=activityPageSchema.parse({schemaVersion:"draftdesk.activity-page.v1",title,url,text});let id=evidenceId;if(!id){const r=await api("activity-evidence",value);id=r.evidenceId;setEvidenceId(id);}await api("jobs",{planId:"creator-activities",evidenceIds:[id]});await onChange();onRun();}catch(e){setError(e instanceof Error?e.message:"分析失败");}finally{setBusy(false);}}
 async function runBatch(){setBusy(true);setError("");try{const selected=batch.filter(x=>activityBatchDecision(x,keywords).eligible).slice(0,24);if(!selected.length)throw Error("没有截止时间明确、未过期且含规则详情的目标活动；请检查采集结果。");const ids:string[]=[];for(const item of selected){const result=await api("activity-evidence",{schemaVersion:"draftdesk.activity-page.v1",title:item.title,url:item.url,text:`平台：${item.platform}\n活动时间原文：${item.dateText}\n截止时间：${item.endsAt}\n${item.text}`});ids.push(result.evidenceId);}await api("jobs",{planId:"creator-activities",evidenceIds:ids,targetKeywords:keywords.slice(0,8)});await onChange();onRun();}catch(e){setError(e instanceof Error?e.message:"批量分析失败");}finally{setBusy(false);}}
 return <section className="surface activity-tools"><h2>从官方活动页导入</h2><p>登录留在你自己的 Chrome / Edge；工作台不接收密码和 Cookie。采集由你手动执行，分析只使用提交的规则，不进行网络搜索。</p>
 <h3>1 · 选择平台并登录</h3><Field label="平台"><select value={platform} onChange={e=>setPlatform(Number(e.target.value))}>{activityPlatforms.map((p,i)=><option key={p.name} value={i}>{p.name}</option>)}</select></Field><a href={activityPlatforms[platform].url} target="_blank" rel="noopener noreferrer">打开{activityPlatforms[platform].name}官方活动入口 ↗</a><p>{activityPlatforms[platform].entry}。在自己的 Chrome / Edge 完成登录；Codex 内置浏览器的登录状态不会同步。工作台不接收账号密码或 Cookie。</p>
 <h3>2 · 自动采集与核对</h3><p><a href="/activity-collector.zip" download>下载开源浏览器采集扩展</a>，解压后在 Chrome / Edge 的“扩展程序”页面开启开发者模式，选择“加载已解压的扩展程序”，选中含 manifest.json 的目录。已安装旧版请点“重新加载”。</p><p>在各平台官方活动页点扩展的“自动采集当前平台”，输入关键词及最多扫描页数。扩展会读取可见活动详情、跳过已过期活动；只有规则和截止时间足够明确的条目才可进入 AI 分析。每个平台导出一个批量 JSON，再逐个导入本页。抖音扫描当前月份，切换月份后可再运行；小红书、快手的年份与规则可能需要核对。不会自动报名或发布。</p>
 <Field label="导入扩展导出的活动 JSON"><input type="file" accept=".json,application/json" disabled={busy} onChange={e=>{void load(e.target.files?.[0]);e.target.value="";}}/></Field>
 <Field label="目标关键词（逗号分隔；同时限制批量采集后的 AI 分析）"><input value={keywordText} disabled={busy} onChange={e=>setKeywordText(e.target.value)} /></Field>
 {batch.length>0&&<section><h3>批量采集预览 · {batch.length} 条</h3><p>只有截止时间明确、未过期、命中关键词且取得规则详情的活动才会提交 AI。过期与摘要线索不会进入分析。</p>{batchWarnings.map((x,i)=><p className="muted" key={i}>{x}</p>)}<ul>{batch.map((item,i)=>{const d=activityBatchDecision(item,keywords);return <li key={i}><strong>{item.platform} · {item.title}</strong> — {d.eligible?"待分析":d.reason} · {item.dateText||"时间未知"}</li>})}</ul><button className="primary" disabled={busy||active||!batch.some(x=>activityBatchDecision(x,keywords).eligible)} onClick={()=>void runBatch()}>{busy?"正在导入…":"导入合格活动并运行 AI 分析"}</button></section>}
 <h3>3 · 预览材料并交给 AI</h3><Field label="活动名称"><input value={title} disabled={busy} onChange={e=>{setTitle(e.target.value);reset();}} maxLength={300}/></Field><Field label="官方活动地址"><input value={url} disabled={busy} onChange={e=>{setUrl(e.target.value);reset();}}/></Field><Field label="规则正文"><textarea rows={8} value={text} disabled={busy} maxLength={12000} onChange={e=>{setText(e.target.value);reset();}}/></Field><p>{text.length} / 12000 字 · 请包含活动年份、截止时间、激励条件和投稿要求。缺失的信息会作为待核实项，不代表完整抓取了活动中心。</p><button className="primary" disabled={busy||active||text.trim().length<50||title.trim().length<3||!url} onClick={()=>void run()}>{busy?"正在提交…":active?"活动分析进行中":"保存规则并分析（模型计费）"}</button>{evidenceId&&<p>原文已保存，失败可重试创建分析任务。</p>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
